# Generated by Django 3.0.14 on 2023-03-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=20)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('datebirth', models.DateField()),
            ],
        ),
    ]
