# Generated by Django 3.0.14 on 2023-03-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pass1', models.CharField(max_length=20)),
            ],
        ),
    ]
